# -- Theme Options --
# Refer to https://jpanther.github.io/congo/docs/configuration/#theme-parameters
# for details about each of these parameters.

colorScheme = "paper" # site override in assets/css/schemes/paper.css
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

fingerprintAlgorithm = "sha256"

[header]
  layout = "basic" # valid options: basic, hamburger, hybrid, custom
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 5

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false
  showComments = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]
